version: "3.4"

services:
  drupal:
    image: drupal:8.8.2
    networks:
      - default_net
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:12.1
    networks:
      - default_net
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - "drupal-postgres:/var/lib/postgresql/data"
networks:
  default_net:
    external: true
volumes:
  drupal-postgres:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
